name: flutter_chat_demo
description: This is the demo for chat app for E-gov

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.14.0+5
  cloud_firestore: ^0.12.11
  fluttertoast: ^3.1.3
  image_picker: ^0.6.1+8
  shared_preferences: ^0.5.3+4
  firebase_storage: ^3.0.6
  cached_network_image: ^1.1.3
  intl: ^0.15.7
  firebase_messaging: ^5.1.6
  flutter_local_notifications: ^0.8.4
  mask_text_input_formatter: ^1.0.5
  country_pickers: ^1.1.0
  firebase_core: ^0.4.1
  flutter_svg: ^0.15.0
  pin_code_fields: ^2.3.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
     - images/img_not_available.jpeg
     - images/teacher.svg
     - images/student.svg